#---------------#
# Site settings #
#---------------#

url: http://UdeP-dis-exp.github.io
title: Diseño Experimental
subtitle: Universidad de Pamplona
simple_search: https://www.google.com/search
description: Guia para el curso de Diseño Experimental
baseurl: ""
permalink: /:categories/:title/
